[package]
name = "rjrssync"
version = "0.1.0"
edition = "2021"
default-run = "rjrssync"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
env_logger = "*"
log="*"
rust-embed = { version = "=6.4.2", features = [ "debug-embed", "include-exclude" ] } # debug-embed Otherwise the behaviour is different in debug vs release builds
tempdir="*"
walkdir="*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.2.1"
filetime = "*"
regex = "1"
aes-gcm = "0.10.1"
aead = {version = "0.5.1", features = ["bytes"]}
base64 = "*"
thousands = "=0.2.0"
map-macro = "=0.2.4"
yaml-rust = "0.4.5"
tempfile = "=3.3.0"
lazy_static = "1.4.0"
bytes = "=1.3.0"
network-interface = "=0.1.5"

[features]
profiling=[]

[profile.profiling]
inherits = "release"
debug = 1