[package]
name = "rjrssync"
version = "0.1.0"
edition = "2021"
default-run = "rjrssync"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
env_logger = "*"
log="*"
rust-embed = { version = "=6.4.2", features = [ "debug-embed", "include-exclude" ] } # debug-embed Otherwise the behaviour is different in debug vs release builds
tempdir="*"
walkdir="*"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.2.1"
filetime = "*"
regex = "1"
aes-gcm = "0.10.1"
aead = {version = "0.5.1", features = ["bytes"]}
base64 = "*"
thousands = "=0.2.0"
yaml-rust = "0.4.5"
lazy_static = "1.4.0"
bytes = "=1.3.0"

# Profiling-only dependencies
serde_json = { version = "1.0", optional = true }

# Dependencies needed for tests/benchmarks, which aren't needed for building on a remote
#if NonRemote
tempfile = "=3.3.0"
map-macro = "=0.2.4"
network-interface = "=0.1.5"
fs_extra = "=1.2.0"
ascii_table = "=4.0.2"
#end

[features]
profiling=["dep:serde_json"]

[profile.profiling]
inherits = "release"
debug = 1

#if NonRemote
[[bench]]
name = "benchmarks"
harness = false
#end