[package]
name = "rjrssync"
version = "0.1.0"
edition = "2021"
default-run = "rjrssync"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
env_logger = "*"
log="*"
rust-embed = { version = "6.4.2", features = [ "debug-embed", "include-exclude" ] } # debug-embed Otherwise the behaviour is different in debug vs release builds
tempdir="*"
walkdir="*"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.2.1"
filetime = "*"
regex = "1"