# This workflow builds and runs unit tests on both Windows and Linux (natively, no WSL).
# No remote platforms are available for testing, so tests that require that are not run.

name: Native

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ build_and_test.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      # Skip tests that require a remote, as this isn't available in this workflow.
      # The "windows-with-wsl" workflow tests remote connection by using WSL.
      run: cargo test --verbose -- --skip "remote_tests::"
