# This workflow builds and runs unit tests on both Windows and Linux, as well as running
# WSL to test remote connection between OSes.

name: Post-Commit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      tmate_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: false

env:
  CARGO_TERM_COLOR: always

jobs:
  # This job builds and runs unit tests on both Windows and Linux (natively, no WSL).
  # No remote platforms are available for testing, so tests that require that are not run.
  native:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      # Skip tests that require a remote, as this isn't available in this workflow.
      # The "windows-with-wsl" workflow tests remote connection by using WSL.
      run: cargo test --verbose -- --skip "remote_tests::"

  # This job sets up a Windows runner with WSL, so that tests that require remote
  # platforms (e.g. a Linux to Windows sync) can be tested.
  remote_platforms:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Vampire/setup-wsl@v1

    # Can't seem to get the windows OpenSSH server installed, as we get an error when adding the optional package.
    # There is an sshd already installed as part of cygwin, but this means that when we log in we get a cygwin prompt, not a windows prompt
    # So instead we use chocolately to install OpenSSH.
    - name: Setup SSH server 1
      shell: pwsh
      run: |
        choco install openssh
        &"C:\Program Files\OpenSSH-Win64\install-sshd.ps1"
        Start-Service sshd
        # For debugging?
        # Start-Job -WorkingDirectory . -ScriptBlock { & 'C:\Program Files\OpenSSH-Win64\sshd.exe' -ddd }

    # Beware that the tmate session runs inside cygwin, so some behaviour doesn't match native windows
    - name: Setup tmate session for debugging (only if enabled)
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.tmate_enabled }}
      uses: mxschmitt/action-tmate@v3

    - name: Setup SSH server 2
      shell: pwsh
      run: |
        mkdir C:\Users\runneradmin\.ssh
        ssh-keygen -f C:\Users\runneradmin\.ssh\id_rsa -q -N '""'

        #TODO: remove match admin group thing from sshd_config so it uses the normal authorized_keys, restart srevice?

        #TODO: use env var for userprofile rather than hardcode?
        cp C:\Users\runneradmin\.ssh\id_rsa.pub C:\Users\runneradmin\.ssh\authorized_keys
        #cp C:\Users\runneradmin\.ssh\id_rsa.pub C:\ProgramData\ssh\administrators_authorized_keys

        &'C:\Program Files\OpenSSH-Win64\FixHostFilePermissions.ps1' -Confirm
        &'C:\Program Files\OpenSSH-Win64\FixUserFilePermissions.ps1' -Confirm

        ssh localhost echo hi
    
    - name: Run remote tests on Windows
      # Only run tests that require a remote, as the other tests are covered by the "native" jobs above.
      # The logic in remote_tests.rs should automatically detect the WSL instance and connect to that
      run: cargo test --verbose -- "remote_tests::"

    - name: Run remote tests on WSL
      # Only run tests that require a remote, as the other tests are covered by the "native" jobs above.
      # The logic in remote_tests.rs should automatically detect the Windows host and connect to that
      shell: wsl-bash {0}
      run: cargo test --verbose -- "remote_tests::"

