# This workflow sets up a Windows runner with WSL, so that tests that require remote
# platforms (e.g. a Linux to Windows sync) can be tested.

name: Windows with WSL

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Vampire/setup-wsl@v1
    
    - name: run something in WSL
      shell: wsl-bash {0}
      run: uname -a
    - name: run something else in WSL
      shell: wsl-bash {0}
      run: ifconfig
    
    - name: run from windows
      run: wsl echo testing from linux
    - name: run from windows
      run: wsl uname -a

#TODO: run both ways (from Linux connecting to remote windows, and from Windows to remote linux)